<Project Sdk="Microsoft.NET.Sdk">


	<PropertyGroup>

		<OutputType>WinExe</OutputType>

		<TargetFramework>net10.0-windows</TargetFramework>

		<UseWPF>true</UseWPF>

		<Nullable>enable</Nullable>
		<ApplicationIcon>analysis.ico</ApplicationIcon>
		<!-- 单文件 -->
		<PublishSingleFile>true</PublishSingleFile>

		<!-- 包含运行环境 -->
		<SelfContained>true</SelfContained>

		<!-- Windows 64位 -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<!-- Application -->
		<AssemblyName>MailScope</AssemblyName>
		<RootNamespace>MailScope</RootNamespace>

		<!-- File information -->
		<Product>MailScope</Product>
		<Company>Xugg1999@outlook.com</Company>
		<Description>MailScope Email Intelligence And Contact Analyzer</Description>
		<Copyright>Copyright © 2026 MailScope</Copyright>

		<!-- Version -->
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		
	</PropertyGroup>


	<ItemGroup>

		<PackageReference Include="MailKit" Version="4.17.0" />

		<PackageReference Include="EPPlus" Version="7.5.0" />

		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />

	</ItemGroup>


</Project>